### ISSUE TITLE
Compile fails during consequent converges

### ISSUE THREAD

**Issue by anuriq** [jrnker/windows_rdp#2]
During 1st converge everything's ok, but on second:

```
================================================================================
Recipe Compile Error in c:/chef/cache/cookbooks/prl-win-build/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `stdout' for "":String

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/windows_rdp/libraries/default.rb:55:in `r_a'
  c:/chef/cache/cookbooks/windows_rdp/recipes/default.rb:34:in `from_file'
  c:/chef/cache/cookbooks/prl-base/recipes/windows.rb:26:in `from_file'
  c:/chef/cache/cookbooks/prl-win-build/recipes/_base_prepare.rb:21:in `from_file'
  c:/chef/cache/cookbooks/prl-win-build/recipes/default.rb:10:in `from_file'

Relevant File Content:
----------------------
c:/chef/cache/cookbooks/windows_rdp/libraries/default.rb:

 48:  def r_a(data_cmd)
 49:      data = r_d(data_cmd)
 50:      if data != nil
 51:        if data.include? "\n"
 52:          data = data.split(/\n/)
 53:        else
 54:          data2 = Array.new
 55>>         data2[0] = data.stdout
 56:          data = data2
 57:        end
 58:      end
 59:      return data
 60:  end 61:

Platform:
---------
x64-mingw32

[2016-08-23T17:35:53+03:00] ERROR: Running exception handlers
[2016-08-23T17:35:53+03:00] ERROR: Exception handlers complete
[2016-08-23T17:35:54+03:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2016-08-23T17:35:54+03:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-08-23T17:35:54+03:00] FATAL: NoMethodError: undefined method `stdout' for "":String
```

**Comment by brunoscota** [comment]
Same to me, everything looks good using kitchen-vagrant but deploying in prod it gives me the same error.

**Comment by Taegost** [comment]
I don't have this issue when working with Vagrant, Virtualbox, and Windows 2012R2
